apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-hpa
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-hpa
        image: registry.k8s.io/hpa-example
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
